### ISSUE TITLE
Errors when about to retrieve dates

### ISSUE THREAD

**Issue by nozric** [clarkdave/DSACancellationChecker#11]
Hi, I'm getting the following error when the script is about to retrieve available dates. The previous script was working perfectly until the DVSA website change in Jan 2017. I've had to update to Python 3.6 (from 2.7) and BeautifulSoup4 on MacOS to account for the recent changes to the script. I thought I had everything installed correctly but wondered if the error was in the script or just the result of me missing something. Hoping someone can help...

---> Connecting to https://driverpracticaltest.direct.gov.uk/login
-----> Sending data:
-------> username = ExxxxxxxxxxxxxxL
-------> password = 3xxxxxx0
---> Connecting to https://driverpracticaltest.direct.gov.uk/manage?execution=e1s1&_eventId=editTestDateTime&csrftoken=HcoUKFYTk7U57lSTkBklvtMKj5ToZU1g
-----> Sending data:
-------> username = ExxxxxxxxxxxxxxL
-------> password = 3xxxxxx0
---> Connecting to https://driverpracticaltest.direct.gov.uk/manage?execution=e1s2&_eventId=proceed
Traceback (most recent call last):
  File "DSAchecker.py", line 186, in <module>
    performUpdate()
  File "DSAchecker.py", line 162, in performUpdate
    datePickerPage.connect()
  File "/Users/axxxxxxxxxxs/Downloads/DSA/DSACheckerClasses.py", line 28, in connect
    self.response = self.opener.open(self.url, binary_data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

**Comment by goodoldme** [comment]
Hello,

Did a quick check and looks like they have changed the website again; the script is broken. I will try and fix the script later today and push the change

-C

**Comment by nozric** [comment]
That's great, thank you!

**Comment by clarkdave** [comment]
@goodoldme thanks for doing this! I have added you as a collaborator \o/

**Comment by goodoldme** [comment]
@clarkdave Cheers!

**Comment by nozric** [comment]
Thanks for the quick fix. Much appreciated. Working perfectly now.
