### ISSUE TITLE
 AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by shkhan922** [clarkdave/DSACancellationChecker#17]
Every time getting this error:
[2018-05-31 @ 02:03]
---> Starting update...
---> Using agent Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
---> Connecting to https://driverpracticaltest.direct.gov.uk/login

---> Connecting to https://driverpracticaltest.direct.gov.uk/login
-----> Sending data:
-------> username = *****
-------> password = 404***
Traceback (most recent call last):
  File "DSAChecker.py", line 226, in <module>
    performUpdate()
  File "DSAChecker.py", line 165, in performUpdate
    dateChangeURL = launcher.html.find(id="date-time-change").get('href')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by shkhan922** [comment]
Can anyone please help here?

**Comment by jbonnett92** [comment]
I have the same problem.

**Comment by saurabhest** [comment]
did you manage to get a solution? I am facing the same issue

**Comment by zoomin87** [comment]
did someone find a solution to this?
