### ISSUE TITLE
How do i fix this 

### ISSUE THREAD

**Issue by Electrik-rich546456** [clarkdave/DSACancellationChecker#19]
I ran `python3 DSAChecker.py` after filling in the info.py 
but i get this error.

`Traceback (most recent call last):
  File "DSAChecker.py", line 226, in <module>
    performUpdate()
  File "DSAChecker.py", line 165, in performUpdate
    dateChangeURL = launcher.html.find(id="date-time-change").get('href')
AttributeError: 'NoneType' object has no attribute 'get'
`

**Comment by mazshar** [comment]
Website has changed considerably so the URLs are probably all different.
