### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by jimanvlad** [clarkdave/DSACancellationChecker#6]
Hi,

Got the following error. Can you let me know if I'm doing anything wrong?

```
[2015-01-10 @ 17:00]
---> Starting update...
---> Connecting to https://driverpracticaltest.direct.gov.uk/login

---> Connecting to https://driverpracticaltest.direct.gov.uk/login
-----> Sending data:
-------> username = <hidden>
-------> password = <hidden>
Traceback (most recent call last):
  File "DSAChecker.py", line 187, in <module>
    performUpdate()
  File "DSAChecker.py", line 145, in performUpdate
    dateChangeURL = launcher.html.find(id="date-time-change").get('href')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by rayic3** [comment]
Hi, 

Did you get any solution to this?

**Comment by sgastol** [comment]
@jimanvlad @rayic3 Nothing wrong with a code, I think is just time when service is off. Don't remember  I guess between 12 to 5 morning.

**Comment by goodoldme** [comment]
The service is available only between 6am and 11;30pm. You'd get this error if you try to access DVSA site any other time.
